export const ACTION_TYPES = {
  LOGIN_START: "LOGIN_START",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGOUT: "LOGOUT",
  GET_COLOMNS_START: "GET_COLOMNS_START",
  GET_COLOMNS_SUCCESS: "GET_COLOMNS_SUCCESS",
  GET_COLOMNS_FAILURE: "GET_COLOMNS_FAILURE",
  POST_COLUMN_START: "POST_COLUMN_START",
  POST_COLUMN_SUCCESS: "POST_COLUMN_SUCCESS",
  POST_COLUMN_FAILURE: "POST_COLUMN_FAILURE",
};
